services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - airflow
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=root
#    volumes:
#      - "pgadmin_conn_data:/var/lib/pgadmin:rw"
#    ports:
#      - "8080:80"
#volumes:
#  pgadmin_conn_data:
#  ny_taxi_postgres_data:

networks:
  airflow:
    external:
      name: week_2_data_ingestion_default

## They need to be in the same network in order to be able to communicate
# network name: pg-network
# DB CONTAINER NEEDS NAME TAG so that pgadmin can find it
#docker network create pg-network
#
#docker run -it \
#-e POSTGRES_USER="root" \
#-e POSTGRES_PASSWORD="root" \
#-e POSTGRES_DB="ny_taxi" \
#-v $(pwd)/ny_taxi_postgres_data:/var/lib/postgresql/data \
#-p 5432:5432 \
#--network=pg-network \
#--name pg-database \
#postgres:13
#
#docker run -it \
#-e PGADMIN_DEFAULT_EMAIL="admin@admin.com" \
#-e PGADMIN_DEFAULT_PASSWORD="root" \
#-p 8081:80 \
#--name pgadmin \
#dpage/pgadmin4

# SCCRIPT
# TODO add carets to selected lines shortcut
#URL="https://nyc-tlc.s3.amazonaws.com/trip+data/yellow_tripdata_2022-01.parquet"
#
#python ingest_data.py \
#--user=root \
#--password=root \
#--host=localhost \
#--port=5432 \
#--db=ny_taxi \
#--table_name=yellow_taxi_data \
#--url=${URL}
#
#URL="https://nyc-tlc.s3.amazonaws.com/trip+data/yellow_tripdata_2022-01.parquet"
#
#docker run -it \
#--network=pg-network \
#taxi_ingest:v001 \
#--user=root \
#--password=root \
#--host=pg-database \
#--port=5432 \
#--db=ny_taxi \
#--table_name=yellow_taxi_data \
#--url=${URL}
